name = "PlasmaBO"
uuid = "89aa2b4b-ed13-41a6-8160-6e24b4388da4"
version = "1.0.0-DEV"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
DataInterpolations = "8"
FFTW = "1"
LinearAlgebra = "1"
QuadGK = "2"
SpecialFunctions = "2"
julia = "1.10"
