name = "PlasmaBO"
uuid = "89aa2b4b-ed13-41a6-8160-6e24b4388da4"
version = "0.1.0"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
DataInterpolations = "8"
LinearAlgebra = "1"
ProgressMeter = "1"
QuadGK = "2"
SpecialFunctions = "2"
Tullio = "0.3"
julia = "1.10"
